"""add unique constraints to authorized_users email and phone

Revision ID: 92db774ea127
Revises: fb0c247e24e3
Create Date: 2026-04-12 20:33:40.352684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92db774ea127'
down_revision: Union[str, Sequence[str], None] = 'fb0c247e24e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authorized_users_email'), 'authorized_users', ['email'], unique=True)
    op.create_index(op.f('ix_authorized_users_phone'), 'authorized_users', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorized_users_phone'), table_name='authorized_users')
    op.drop_index(op.f('ix_authorized_users_email'), table_name='authorized_users')
    # ### end Alembic commands ###
