"""create rfid_assignments table

Revision ID: 9a93b7cb1bee
Revises: c88e3a66016a
Create Date: 2026-04-11 23:43:52.387581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a93b7cb1bee'
down_revision: Union[str, Sequence[str], None] = 'c88e3a66016a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_card_id', sa.Integer(), nullable=False),
    sa.Column('authorized_user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_staff_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_staff_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['authorized_user_id'], ['authorized_users.id'], ),
    sa.ForeignKeyConstraint(['rfid_card_id'], ['rfid_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_assignments_assigned_by_staff_id'), 'rfid_assignments', ['assigned_by_staff_id'], unique=False)
    op.create_index(op.f('ix_rfid_assignments_authorized_user_id'), 'rfid_assignments', ['authorized_user_id'], unique=False)
    op.create_index(op.f('ix_rfid_assignments_id'), 'rfid_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_rfid_assignments_rfid_card_id'), 'rfid_assignments', ['rfid_card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfid_assignments_rfid_card_id'), table_name='rfid_assignments')
    op.drop_index(op.f('ix_rfid_assignments_id'), table_name='rfid_assignments')
    op.drop_index(op.f('ix_rfid_assignments_authorized_user_id'), table_name='rfid_assignments')
    op.drop_index(op.f('ix_rfid_assignments_assigned_by_staff_id'), table_name='rfid_assignments')
    op.drop_table('rfid_assignments')
    # ### end Alembic commands ###
