"""create rfid_cards table

Revision ID: c88e3a66016a
Revises: e8894bf13fc5
Create Date: 2026-04-11 23:31:55.379410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88e3a66016a'
down_revision: Union[str, Sequence[str], None] = 'e8894bf13fc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('card_label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfid_cards_id'), 'rfid_cards', ['id'], unique=False)
    op.create_index(op.f('ix_rfid_cards_uid'), 'rfid_cards', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfid_cards_uid'), table_name='rfid_cards')
    op.drop_index(op.f('ix_rfid_cards_id'), table_name='rfid_cards')
    op.drop_table('rfid_cards')
    # ### end Alembic commands ###
