"""create access_logs table

Revision ID: fb0c247e24e3
Revises: d5474daf3ae4
Create Date: 2026-04-12 00:26:13.312969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0c247e24e3'
down_revision: Union[str, Sequence[str], None] = 'd5474daf3ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('rfid_card_id', sa.Integer(), nullable=True),
    sa.Column('authorized_user_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('uid_scanned', sa.String(length=100), nullable=False),
    sa.Column('access_status', sa.String(length=20), nullable=False),
    sa.Column('access_direction', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('door_opened', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['rfid_assignments.id'], ),
    sa.ForeignKeyConstraint(['authorized_user_id'], ['authorized_users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['rfid_card_id'], ['rfid_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_assignment_id'), 'access_logs', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_access_logs_authorized_user_id'), 'access_logs', ['authorized_user_id'], unique=False)
    op.create_index(op.f('ix_access_logs_device_id'), 'access_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_rfid_card_id'), 'access_logs', ['rfid_card_id'], unique=False)
    op.create_index(op.f('ix_access_logs_uid_scanned'), 'access_logs', ['uid_scanned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_logs_uid_scanned'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_rfid_card_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_device_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_authorized_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_assignment_id'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
